-- Example catalogue sold by TFS so the marketplace isn't empty on day one (prices are examples).
-- Prices and details are placeholders: staff edit or hide them in Admin → Products.

insert into public.products (category, name, description, unit, price, min_qty, origin_country, lead_time_days, specs, status) values
  ('wood', 'Pine planks, kiln dried (C24)',
   'Structural pine planks, planed all round, kiln dried to 18% moisture. For framing, roofing and joinery.',
   'm3', 485.00, 2, 'Sweden', 14,
   '[{"label":"Thickness","value":"45 mm"},{"label":"Width","value":"145 mm"},{"label":"Length","value":"4.2 m"},{"label":"Grade","value":"C24"}]', 'active'),
  ('wood', 'Oak boards, rustic grade',
   'European oak boards, air and kiln dried, square edged. For flooring, furniture and interior work.',
   'm3', 1450.00, 1, 'Poland', 21,
   '[{"label":"Thickness","value":"27 mm"},{"label":"Width","value":"120–200 mm"},{"label":"Moisture","value":"8–10%"}]', 'active'),
  ('wood', 'Birch plywood, 18 mm',
   'Full birch plywood sheets, BB/CP grade, exterior glue (WBP).',
   'piece', 62.50, 20, 'Finland', 10,
   '[{"label":"Size","value":"2500 × 1250 mm"},{"label":"Thickness","value":"18 mm"},{"label":"Glue","value":"WBP / EN 314-2 class 3"}]', 'active'),
  ('wood', 'MDF boards, moisture resistant',
   'Moisture-resistant MDF for kitchens and bathrooms. Smooth surface for painting.',
   'piece', 28.90, 30, 'Germany', 7,
   '[{"label":"Size","value":"2440 × 1220 mm"},{"label":"Thickness","value":"18 mm"}]', 'active'),
  ('doors', 'Interior door, white primed, flush',
   'Flush interior door with honeycomb core, white primed and ready to paint.',
   'piece', 89.00, 10, 'Netherlands', 10,
   '[{"label":"Size","value":"830 × 2015 mm"},{"label":"Thickness","value":"40 mm"},{"label":"Core","value":"Honeycomb"}]', 'active'),
  ('doors', 'Solid oak interior door',
   'Solid oak door with five horizontal panels, oiled finish.',
   'piece', 345.00, 2, 'Poland', 21,
   '[{"label":"Size","value":"880 × 2115 mm"},{"label":"Thickness","value":"40 mm"},{"label":"Finish","value":"Natural oil"}]', 'active'),
  ('doors', 'Steel security front door',
   'Insulated steel entrance door with multi-point lock, RC2 burglary resistance.',
   'piece', 690.00, 1, 'Turkey', 30,
   '[{"label":"Size","value":"980 × 2090 mm"},{"label":"Security","value":"RC2"},{"label":"U-value","value":"1.3 W/m²K"}]', 'active'),
  ('ceramics', 'Porcelain floor tile 60×60, matt grey',
   'Rectified porcelain tile, through-body colour, R10 anti-slip. For indoor floors and walls.',
   'm2', 18.50, 50, 'Spain', 14,
   '[{"label":"Size","value":"600 × 600 mm"},{"label":"Thickness","value":"9 mm"},{"label":"Slip rating","value":"R10"}]', 'active'),
  ('ceramics', 'Glazed wall tile 30×60, gloss white',
   'Classic gloss white ceramic wall tile for kitchens and bathrooms.',
   'm2', 12.90, 40, 'Portugal', 14,
   '[{"label":"Size","value":"300 × 600 mm"},{"label":"Finish","value":"Gloss"}]', 'active'),
  ('ceramics', 'Marble-look porcelain slab 120×60',
   'Large-format polished porcelain with Calacatta marble look.',
   'm2', 34.00, 30, 'Italy', 21,
   '[{"label":"Size","value":"1200 × 600 mm"},{"label":"Finish","value":"Polished"}]', 'active'),
  ('building', 'Cement CEM II 42.5, 25 kg',
   'General-purpose Portland composite cement in 25 kg bags, delivered on pallets of 56 bags.',
   'pallet', 395.00, 1, 'Belgium', 7,
   '[{"label":"Bags per pallet","value":"56 × 25 kg"},{"label":"Class","value":"CEM II/B-M 42.5 N"}]', 'active'),
  ('building', 'Rock wool insulation slabs',
   'Rock wool slabs for walls and roofs, non-combustible (Euroclass A1).',
   'm2', 7.40, 100, 'Netherlands', 7,
   '[{"label":"Thickness","value":"100 mm"},{"label":"Lambda","value":"0.035 W/mK"},{"label":"Fire class","value":"A1"}]', 'active');

-- Product images for the examples ship with the website in /public/products.
update public.products p set images = array[v.img]
from (values
  ('Pine planks, kiln dried (C24)', '/products/pine-planks.jpg'),
  ('Oak boards, rustic grade', '/products/oak-boards.jpg'),
  ('Birch plywood, 18 mm', '/products/birch-plywood.jpg'),
  ('MDF boards, moisture resistant', '/products/mdf-boards.jpg'),
  ('Interior door, white primed, flush', '/products/white-door.jpg'),
  ('Solid oak interior door', '/products/oak-door.jpg'),
  ('Steel security front door', '/products/steel-door.jpg'),
  ('Porcelain floor tile 60×60, matt grey', '/products/porcelain-tile.jpg'),
  ('Glazed wall tile 30×60, gloss white', '/products/wall-tile.jpg'),
  ('Marble-look porcelain slab 120×60', '/products/marble-slab.jpg'),
  ('Cement CEM II 42.5, 25 kg', '/products/cement-pallet.jpg'),
  ('Rock wool insulation slabs', '/products/rock-wool.jpg')
) as v(name, img)
where p.name = v.name and p.supplier_id is null and cardinality(p.images) = 0;
